Repository nephio-project/api, pull requests merged in 2023-04, with the labels that each got.

#3 added maxNFConnections in capacity
  nf_requirements/v1alpha1/capacity.go
Labels: area/package-specialization

#9 Align with nephio repo Makefile and prow config
  .golangci.yml
  .prow.yaml
  Makefile
  nf_requirements/v1alpha1/interface_types.go
Labels: approved

#10 Validate fn added to support the interface lib
  go.mod
  go.sum
  nf_requirements/v1alpha1/capacity_types.go
  nf_requirements/v1alpha1/dnn_types.go
  nf_requirements/v1alpha1/groupversion_info.go
  nf_requirements/v1alpha1/interface.go
  nf_requirements/v1alpha1/interface_interfaces.go
  nf_requirements/v1alpha1/interface_test.go
  nf_requirements/v1alpha1/interface_types.go
Labels: approved, lgtm

#11 Nfdeployment CR specifications for AMF, SMF, UPF
  Makefile
  config/crd/bases/req.nephio.org_capacities.yaml
  config/crd/bases/workload.nephio.org_amfdeployments.yaml
  config/crd/bases/workload.nephio.org_smfdeployments.yaml
  config/crd/bases/workload.nephio.org_upfdeployments.yaml
  nf_deployments/v1alpha1/amf_deployment_types.go
  nf_deployments/v1alpha1/groupversion_info.go
  nf_deployments/v1alpha1/nf_deployment_types.go
  nf_deployments/v1alpha1/smf_deployment_types.go
  nf_deployments/v1alpha1/upf_deployment_types.go
  nf_deployments/v1alpha1/zz_generated.deepcopy.go
  nf_requirements/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm

#14 Normalize mismathing json and yaml tags of the DataNetwork.NetworkIns…
  nf_requirements/v1alpha1/dnn_types.go
Labels: approved, lgtm

#13 Prow job update
  .prow.yaml
  Makefile
Labels: needs-ok-to-test, approved, lgtm

#16 Bumped gotests version
  .prow.yaml
Labels: needs-ok-to-test, approved, lgtm

#12 added status to reflect info back to the cr
  config/crd/bases/req.nephio.org_datanetworks.yaml
  config/crd/bases/req.nephio.org_interfaces.yaml
  config/crd/bases/workload.nephio.org_amfdeployments.yaml
  config/crd/bases/workload.nephio.org_smfdeployments.yaml
  config/crd/bases/workload.nephio.org_upfdeployments.yaml
  go.mod
  go.sum
  nf_requirements/v1alpha1/dnn_types.go
  nf_requirements/v1alpha1/interface_types.go
  nf_requirements/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, ok-to-test

#18 DataNetworkStatus: Add status to all individual pools
  nf_requirements/v1alpha1/dnn_types.go
  nf_requirements/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm
