Repository nephio-project/api, pull requests merged in 2025-02, with the labels that each got.

#66 Update O2IMS provisionedResources to provisionedResourceSet per CRD
  config/crd/bases/o2ims.provisioning.oran.org_provisioningrequests.yaml
Labels: approved, lgtm

#67 Add CRDs for ORAN Focom Operator Usecase
  config/crd/bases/focom.nephio.org_focomprovisioningrequests.yaml
  config/crd/bases/focom.nephio.org_oclouds.yaml
  config/crd/bases/provisioning.oran.org_templateinfoes.yaml
Labels: area/workload-cluster, sig/automation, approved, lgtm

#68 add missing license headers
  Makefile
Labels: needs-ok-to-test, approved, lgtm
